---
  - hosts: all
    become: true

    tasks:

      - name: install packages 
        package:
          name: nginx,uwsgi,uwsgi-plugin-python3,postgresql,python3-venv
          state: latest


      - name: Add django
        user: 
          name: django
          shell: /bin/bash

      - firewalld:
          service: http
          permanent: yes
          state: enabled

      - git:
          repo: 'https://github.com/jfmatth/aim-django.git'
          version: movetodev
          dest: /home/django/mysite
        become: yes
        become_user: django

      - pip:
          requirements: /home/django/mysite/requirements.txt
          virtualenv : /home/django/vpython3
          virtualenv_python: python3
        become: yes
        become_user: django

      - file:
          src: /home/django/mysite/uwsgi_mysite.ini
          dest: /etc/uwsgi/apps-enabled/uwsgi_mysite.ini
          state: link
