---
  - hosts: all
    become: true

    tasks:

      - name: Remove Sendmail
        apt:
          name: sendmail
          state: absent

      - name: Remove Postfix
        apt:
          name: postfix
          state: absent

      - name: Remove apache2
        apt:
          name: apache2
          state: absent

      - name: Patch everything
        apt:
          name: "*"
          state: latest
          force_apt_get: true

      - name: Reboot
        reboot:
