---
  - hosts: all
    become: true

    tasks:

      - name: Remove Sendmail
        package:
          name: sendmail
          state: absent

      - name: Remove Postfix
        package:
          name: postfix
          state: absent

      - name: Remove apache2
        package:
          name: apache2
          state: absent

      - name: Patch everything
        yum:
          name: "*"
          state: latest

      - name: Reboot
        reboot:
