---
  - hosts: all
    become: true

    tasks:

      - name: Remove Sendmail
        package:
          name: sendmail
          state: absent

      - name: Remove Postfix
        package:
          name: postfix
          state: absent

      - name: Remove apache2
        package:
          name: apache2
          state: absent

      - name: Install Hyper-V tools
        package:
          name: linux-azure
          state: latest
        when: hyperv

      - name: Patch everything
        apt:
          name: "*"
          state: latest
          force_apt_get: true

        when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

      - name: Reboot
        reboot:
